### ISSUE TITLE
Dashboard should be deployed for dev env

### ISSUE THREAD

**Issue by sirpy** [GoodDollar/GoodDashboard#12]
Definition of Done
- deploy new heroku node
- uses latest smart contracts package
- available at dashboard.gooddollar.org
- freeze current dashboard version in branch "eToro"
- eToro heroku dashboard should use "eToro" branch
- remove "transaction survey" related stuff
- remove saving to ipfs (currently its broken)

**Comment by yaroslav-fedyshyn-nordwhale** [comment]
@serdiukov-o-nordwhale 

I am done with the last two points.
Also, I updated the dashboard to use the latest smart contracts

**Comment by serdiukov-o-nordwhale** [comment]
@sirpy 
I'm stuck with permissions on Heroku. Asked you for them in Slack

![image.png](https://images.zenhubusercontent.com/5e6e2ca830bce88543e4cd2a/aea12519-b725-4138-9a12-4670d95aa9a8)

![image.png](https://images.zenhubusercontent.com/5e6e2ca830bce88543e4cd2a/1368c71a-9df6-4770-9781-db866b264cdd)

**Comment by serdiukov-o-nordwhale** [comment]
@sirpy  Now i stuck with the repo permissions:

![image.png](https://images.zenhubusercontent.com/5e6e2ca830bce88543e4cd2a/5f98b07c-1eb5-4290-85db-839a5195e4b1)

Repository shows as connected but actually
i couldn’t select branch,
entering a name won’t work - automatic deployment won’t enable
on refresh “connected” repository disappears

**Comment by serdiukov-o-nordwhale** [comment]
Almost done, just a few things todo:

1. configure dynos (requires first deploy)
2. add ssl (required paid dynos and first deploy)
3. update env congifs

@sirpy Asked me do not deploy so pp 1-2 were skipped

About p. 3 - could you please provide me env values should be set for
GUN_PUBLIC_URL
MONGO_DB_URI
NETWORK
(currently etoro's gun, mongo & network are used)

Also, probably some other env vars should be changed
Thanks!

**Comment by sirpy** [comment]
@yaroslav-fedyshyn-nordwhale @serdiukov-o-nordwhale
i've set the correct env
i've commited some fixes

survey wasn't removed.
1. on server remove calls to update survey (dont remove related files)
2. on client remove survey related endpoints
3. on client on hover on address shows profile, to support mobile add support to also onclick

**Comment by serdiukov-o-nordwhale** [comment]
> @yaroslav-fedyshyn-nordwhale @serdiukov-o-nordwhale
> i've set the correct env
> i've commited some fixes
> 
> survey wasn't removed.
> 
> 1. on server remove calls to update survey (dont remove related files)
> 2. on client remove survey related endpoints
> 3. on client on hover on address shows profile, to support mobile add support to also onclick

fixed in https://github.com/GoodDollar/GoodDashboard/pull/17
