### ISSUE TITLE
Anonymized transaction data collected (from survey)

### ISSUE THREAD

**Issue by AlexeyKosinski** [GoodDollar/GoodDashboard#2]
Show anonymized transaction data collected from survey. ( total for each kind of answer )
- [x] add endpoint to dashboard backend which gives anonymized transaction data collected (from survey)

**Comment by StanislavShevchenko** [comment]
@sirpy @AlexeyKosinski @Nordwhale 

In the UpdateData method, I will add logic that will go to the gun and take polling data. then I group them in this format
date --- amount (A product) --- amount (A service) --- amount (Other)
And save in MongoBD.
Request to the endpoint I take the grouped data from mongoDB

**Comment by sirpy** [comment]
@AlexeyKosinski @StanislavShevchenko 
We just need plain list of survey results exportable as csv. no need for grouping, just plain list with pager

**Comment by AlexeyKosinski** [comment]
hmm. I think we need some graph by days like this
![image.png](https://images.zenhubusercontent.com/5d53b85120024557db05e3ba/f9040519-110d-45fa-8c2e-2d8bca3bf67b)
or aggregation graph for all period

**Comment by AlexeyKosinski** [comment]
ok. how do u imagine this `plain list with pager`:

for ex table like table:
![image.png](https://images.zenhubusercontent.com/5d53b85120024557db05e3ba/43f9179b-573d-433d-9852-80b7c80b1519)
<< < 1 2 3 4 5 > >> 
@sirpy is it what u expect ?

**Comment by sirpy** [comment]
yes.
exportable to csv (the whole list).
