### ISSUE TITLE
Fix collecting admin survey data

### ISSUE THREAD

**Issue by AlexeyKosinski** [GoodDollar/GoodDashboard#7]
in the admin dashboard, we see survey data only until 24th of December
u need to check and fix to collect whole survey data

DOD:
- [ ] survey page has whole survey data

**Comment by AlexeyKosinski** [comment]
@sirpy 
we have problem on dashboard. this is await this.ipfslog.ready  aways wait. and server can’t start to collect data scince 24 Dec. Now I switched off ipfs from dashboard to start collect data

@AnastasiiaOdnoshevna can u test this again, please?

**Comment by AnastasiiaOdnoshevna** [comment]
Checked on the eWallet 12.1
All surveys are collecting.
